---
 version: "3"
 services:
    app:
      container_name: cont1
      build: ./Docker-app
      ports:
       - "888:80"

    db:
      container_name: devopsdb
      build: ./Docker-db
      ports:
       - "3306:3306"
